In [66]:
!pip install category_encoders
import pandas as pd
import numpy as np 

import seaborn as sns 
import matplotlib.pylab as plt
%matplotlib inline


from scipy.stats import boxcox
from scipy.stats.mstats import normaltest

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score 
from sklearn.metrics import mean_squared_error
from category_encoders import BinaryEncoder



from sklearn.pipeline import Pipeline

Collecting category_encoders
  Downloading category_encoders-2.6.2-py2.py3-none-any.whl (81 kB)
     -------------------------------------- 81.8/81.8 kB 286.4 kB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.0 in c:\users\begat\anaconda3\lib\site-packages (from category_encoders) (1.23.5)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\begat\anaconda3\lib\site-packages (from category_encoders) (1.3.0)
Requirement already satisfied: pandas>=1.0.5 in c:\users\begat\anaconda3\lib\site-packages (from category_encoders) (1.5.3)
Requirement already satisfied: scipy>=1.0.0 in c:\users\begat\anaconda3\lib\site-packages (from category_encoders) (1.10.0)
Requirement already satisfied: patsy>=0.5.1 in c:\users\begat\anaconda3\lib\site-packages (from category_encoders) (0.5.3)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\begat\anaconda3\lib\site-packages (from category_encoders) (0.13.5)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\begat\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\begat\anaconda3\lib\site-packages (from pandas>=1.0.5->category_encoders) (2022.7)
Requirement already satisfied: six in c:\users\begat\anaconda3\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\begat\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (2.2.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\begat\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.1.1)
Requirement already satisfied: packaging>=21.3 in c:\users\begat\anaconda3\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (22.0)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.6.2

I have just imported the modules that I will be needing for this work.

In [17]:
df = pd.read_csv('CarPrice_Assignment.csv') 
# Importing the data file

## Getting to know more about my data

In [18]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [19]:
sum(df.duplicated(subset = 'car_ID')) == 0 
# This means that the sum of duplicated values in our dataset is null
#which simply means that the ID is not a really useful feature for us

True

I have began the features engineering and data preprocessing of the data. I see that there are some features like 'symboling', 'CarName', and 'car_ID', that do not need to be used by me and the model... so i am going to drop them

In [20]:
df['CarName'].unique()

array(['alfa-romero giulia', 'alfa-romero stelvio',
       'alfa-romero Quadrifoglio', 'audi 100 ls', 'audi 100ls',
       'audi fox', 'audi 5000', 'audi 4000', 'audi 5000s (diesel)',
       'bmw 320i', 'bmw x1', 'bmw x3', 'bmw z4', 'bmw x4', 'bmw x5',
       'chevrolet impala', 'chevrolet monte carlo', 'chevrolet vega 2300',
       'dodge rampage', 'dodge challenger se', 'dodge d200',
       'dodge monaco (sw)', 'dodge colt hardtop', 'dodge colt (sw)',
       'dodge coronet custom', 'dodge dart custom',
       'dodge coronet custom (sw)', 'honda civic', 'honda civic cvcc',
       'honda accord cvcc', 'honda accord lx', 'honda civic 1500 gl',
       'honda accord', 'honda civic 1300', 'honda prelude',
       'honda civic (auto)', 'isuzu MU-X', 'isuzu D-Max ',
       'isuzu D-Max V-Cross', 'jaguar xj', 'jaguar xf', 'jaguar xk',
       'maxda rx3', 'maxda glc deluxe', 'mazda rx2 coupe', 'mazda rx-4',
       'mazda glc deluxe', 'mazda 626', 'mazda glc', 'mazda rx-7 gs',
       'mazda glc 4', 'mazda glc custom l', 'mazda glc custom',
       'buick electra 225 custom', 'buick century luxus (sw)',
       'buick century', 'buick skyhawk', 'buick opel isuzu deluxe',
       'buick skylark', 'buick century special',
       'buick regal sport coupe (turbo)', 'mercury cougar',
       'mitsubishi mirage', 'mitsubishi lancer', 'mitsubishi outlander',
       'mitsubishi g4', 'mitsubishi mirage g4', 'mitsubishi montero',
       'mitsubishi pajero', 'Nissan versa', 'nissan gt-r', 'nissan rogue',
       'nissan latio', 'nissan titan', 'nissan leaf', 'nissan juke',
       'nissan note', 'nissan clipper', 'nissan nv200', 'nissan dayz',
       'nissan fuga', 'nissan otti', 'nissan teana', 'nissan kicks',
       'peugeot 504', 'peugeot 304', 'peugeot 504 (sw)', 'peugeot 604sl',
       'peugeot 505s turbo diesel', 'plymouth fury iii',
       'plymouth cricket', 'plymouth satellite custom (sw)',
       'plymouth fury gran sedan', 'plymouth valiant', 'plymouth duster',
       'porsche macan', 'porcshce panamera', 'porsche cayenne',
       'porsche boxter', 'renault 12tl', 'renault 5 gtl', 'saab 99e',
       'saab 99le', 'saab 99gle', 'subaru', 'subaru dl', 'subaru brz',
       'subaru baja', 'subaru r1', 'subaru r2', 'subaru trezia',
       'subaru tribeca', 'toyota corona mark ii', 'toyota corona',
       'toyota corolla 1200', 'toyota corona hardtop',
       'toyota corolla 1600 (sw)', 'toyota carina', 'toyota mark ii',
       'toyota corolla', 'toyota corolla liftback',
       'toyota celica gt liftback', 'toyota corolla tercel',
       'toyota corona liftback', 'toyota starlet', 'toyota tercel',
       'toyota cressida', 'toyota celica gt', 'toyouta tercel',
       'vokswagen rabbit', 'volkswagen 1131 deluxe sedan',
       'volkswagen model 111', 'volkswagen type 3', 'volkswagen 411 (sw)',
       'volkswagen super beetle', 'volkswagen dasher', 'vw dasher',
       'vw rabbit', 'volkswagen rabbit', 'volkswagen rabbit custom',
       'volvo 145e (sw)', 'volvo 144ea', 'volvo 244dl', 'volvo 245',
       'volvo 264gl', 'volvo diesel', 'volvo 246'], dtype=object)

We are going to only use the company name so that we are able to use the carName as well

In [21]:
df['brand'] = df.CarName.str.split(' ').str.get(0).str.lower()

In [22]:
df.brand.unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'maxda', 'mazda', 'buick', 'mercury',
       'mitsubishi', 'nissan', 'peugeot', 'plymouth', 'porsche',
       'porcshce', 'renault', 'saab', 'subaru', 'toyota', 'toyouta',
       'vokswagen', 'volkswagen', 'vw', 'volvo'], dtype=object)

In [23]:
df['brand'] = df['brand'].replace(['maxda'], 'mazda')
df['brand'] = df['brand'].replace(['porcshce'], 'porsche')
df['brand'] = df['brand'].replace(['toyouta'], 'toyota')
df['brand'] = df['brand'].replace(['vokswagen', 'vw'], 'volkswagen')

In [24]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,brand
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,alfa-romero
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,alfa-romero
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,alfa-romero
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0,audi
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0,audi

In [25]:
df.drop(['car_ID', 'symboling', 'CarName'], axis=1, inplace=True)

In [26]:
df.head(15)
# our new data now looks good!

,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,brand
0,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.000,alfa-romero
1,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.000,alfa-romero
2,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.000,alfa-romero
3,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.000,audi
4,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.000,audi
5,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,53.1,...,mpfi,3.19,3.40,8.5,110,5500,19,25,15250.000,audi
6,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,55.7,...,mpfi,3.19,3.40,8.5,110,5500,19,25,17710.000,audi
7,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,55.7,...,mpfi,3.19,3.40,8.5,110,5500,19,25,18920.000,audi
8,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,55.9,...,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.000,audi
9,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,52.0,...,mpfi,3.13,3.40,7.0,160,5500,16,22,17859.167,audi
10,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,...,mpfi,3.50,2.80,8.8,101,5800,23,29,16430.000,bmw
11,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3,...,mpfi,3.50,2.80,8.8,101,5800,23,29,16925.000,bmw
12,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,...,mpfi,3.31,3.19,9.0,121,4250,21,28,20970.000,bmw
13,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3,...,mpfi,3.31,3.19,9.0,121,4250,21,28,21105.000,bmw
14,gas,std,four,sedan,rwd,front,103.5,189.0,66.9,55.7,...,mpfi,3.31,3.19,9.0,121,4250,20,25,24565.000,bmw

In [27]:
df.describe()

,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fueltype          205 non-null    object
 1   aspiration        205 non-null    object
 2   doornumber        205 non-null    object
 3   carbody           205 non-null    object
 4   drivewheel        205 non-null    object
 5   enginelocation    205 non-null    object
 6   wheelbase         205 non-null    float64
 7   carlength         205 non-null    float64
 8   carwidth          205 non-null    float64
 9   carheight         205 non-null    float64
 10  curbweight        205 non-null    int64
 11  enginetype        205 non-null    object
 12  cylindernumber    205 non-null    object
 13  enginesize        205 non-null    int64
 14  fuelsystem        205 non-null    object
 15  boreratio         205 non-null    float64
 16  stroke            205 non-null    float64
 17  compressionratio  205 non-null    float64
 18  horsepower        205 non-null    int64
 19  peakrpm           205 non-null    int64
 20  citympg           205 non-null    int64
 21  highwaympg        205 non-null    int64
 22  price             205 non-null    float64
 23  brand             205 non-null    object
dtypes: float64(8), int64(6), object(10)
memory usage: 38.6+ KB

from this information, I can see that there is no null data at all... so i can proceed into features encoding so that we will have
numbers for the model to work with

In [29]:
df.shape

(205, 24)

#                                             Features Engineering

### Drivewheel column

In [46]:
df.drivewheel.unique()

array(['rwd', 'fwd', '4wd'], dtype=object)

In [47]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [49]:
encoder.fit(df[['drivewheel']])

OneHotEncoder()

In [50]:
drive_wheel_encoded = encoder.transform(df[['drivewheel']])

In [53]:
drive_wheel_encoded

<205x3 sparse matrix of type '<class 'numpy.float64'>'
	with 205 stored elements in Compressed Sparse Row format>

In [55]:
drive_wheel_encoded = drive_wheel_encoded.toarray()

In [56]:
drive_wheel_encoded

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [77]:
new_drive_wheel = pd.DataFrame(drive_wheel_encoded, columns=encoder.get_feature_names_out(['drivewheel']))
print(new_drive_wheel)#new drivewheel value

     drivewheel_4wd  drivewheel_fwd  drivewheel_rwd
0               0.0             0.0             1.0
1               0.0             0.0             1.0
2               0.0             0.0             1.0
3               0.0             1.0             0.0
4               1.0             0.0             0.0
..              ...             ...             ...
200             0.0             0.0             1.0
201             0.0             0.0             1.0
202             0.0             0.0             1.0
203             0.0             0.0             1.0
204             0.0             0.0             1.0

[205 rows x 3 columns]

### Fueltype Column

In [62]:
df.fueltype.value_counts()

gas       185
diesel     20
Name: fueltype, dtype: int64

In [74]:
to_encode_fueltype = pd.DataFrame(df['fueltype'])
binary_encoder = BinaryEncoder()
#we are using binary encoder because we see that gas has a lot more values
#than diesel. Binary encoder is a lot more effecient to use in such cases than One Hot encoder

In [69]:
binary_encoder.fit(to_encode_fueltype)

     fueltype_0  fueltype_1
0             0           1
1             0           1
2             0           1
3             0           1
4             0           1
..          ...         ...
200           0           1
201           0           1
202           0           1
203           1           0
204           0           1

[205 rows x 2 columns]

In [71]:
new_fuel_type = binary_encoder.transform(to_encode_fueltype)

In [72]:
new_fuel_type #new fueltype value

     fueltype_0  fueltype_1
0             0           1
1             0           1
2             0           1
3             0           1
4             0           1
..          ...         ...
200           0           1
201           0           1
202           0           1
203           1           0
204           0           1

[205 rows x 2 columns]

In [89]:
new_fuel_type_columns = ['fueltype_diesel', 'fueltype_gas']
new_fuel_type.columns = new_fuel_type_columns
new_fuel_type

     fueltype_diesel  fueltype_gas
0                  0             1
1                  0             1
2                  0             1
3                  0             1
4                  0             1
..               ...           ...
200                0             1
201                0             1
202                0             1
203                1             0
204                0             1

[205 rows x 2 columns]

The change has been made

### Aspiration column

In [81]:
df.aspiration.value_counts()

std      168
turbo     37
Name: aspiration, dtype: int64

#we have the same situation here so we are still going to use binary encoding

In [90]:
binary_encoder.fit(df['aspiration'])

BinaryEncoder(cols=['aspiration'],
              mapping=[{'col': 'aspiration',
                        'mapping':     aspiration_0  aspiration_1
 1             0             1
 2             1             0
-1             0             0
-2             0             0}])

In [106]:
new_aspiration = binary_encoder.transform(df['aspiration'])
new_aspiration_columns = ['new_aspiration_turbo', 'new_aspiration_std']

In [107]:
new_aspiration.columns = new_aspiration_columns

In [109]:
new_aspiration.head(-5) #new aspiration value

     new_aspiration_turbo  new_aspiration_std
0                       0                   1
1                       0                   1
2                       0                   1
3                       0                   1
4                       0                   1
..                    ...                 ...
195                     0                   1
196                     0                   1
197                     0                   1
198                     1                   0
199                     1                   0

[200 rows x 2 columns]

In [111]:
df.head()

,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,brand
0,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,alfa-romero
1,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,alfa-romero
2,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,alfa-romero
3,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0,audi
4,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0,audi

### Doornumber Column

In [112]:
df.doornumber.value_counts()

four    115
two      90
Name: doornumber, dtype: int64

In [113]:
binary_encoder.fit(df['doornumber'])
new_doornumber = binary_encoder.transform(df['doornumber'])

In [125]:
door_mapping = {'two': 2, 'four': 4}

# Applying the ordinal encoding
df['doornumber'] = df['doornumber'].map(door_mapping)

In [127]:
df.head()

,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,brand
0,gas,std,2,convertible,rwd,front,88.6,168.8,64.1,48.8,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,alfa-romero
1,gas,std,2,convertible,rwd,front,88.6,168.8,64.1,48.8,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,alfa-romero
2,gas,std,2,hatchback,rwd,front,94.5,171.2,65.5,52.4,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,alfa-romero
3,gas,std,4,sedan,fwd,front,99.8,176.6,66.2,54.3,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0,audi
4,gas,std,4,sedan,4wd,front,99.4,176.6,66.4,54.3,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0,audi

we have successfully converted the values on our door number column

### Carbody Column

In [128]:
df.carbody.value_counts()

sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: carbody, dtype: int64

In [130]:
encoder.fit(df[['carbody']])

OneHotEncoder()

In [137]:
car_body_encoded = encoder.transform(df[['carbody']])
car_body_encoded = car_body_encoded.toarray()
new_car_body = pd.DataFrame(car_body_encoded, columns=encoder.get_feature_names_out(['carbody']))
print (new_car_body) # new carbody values

     carbody_convertible  carbody_hardtop  carbody_hatchback  carbody_sedan  \
0                    1.0              0.0                0.0            0.0
1                    1.0              0.0                0.0            0.0
2                    0.0              0.0                1.0            0.0
3                    0.0              0.0                0.0            1.0
4                    0.0              0.0                0.0            1.0
..                   ...              ...                ...            ...
200                  0.0              0.0                0.0            1.0
201                  0.0              0.0                0.0            1.0
202                  0.0              0.0                0.0            1.0
203                  0.0              0.0                0.0            1.0
204                  0.0              0.0                0.0            1.0

     carbody_wagon
0              0.0
1              0.0
2              0.0
3              0.0
4              0.0
..             ...
200            0.0
201            0.0
202            0.0
203            0.0
204            0.0

[205 rows x 5 columns]

In [144]:
df.brand.value_counts()

toyota         32
nissan         18
mazda          17
mitsubishi     13
honda          13
volkswagen     12
subaru         12
peugeot        11
volvo          11
dodge           9
buick           8
bmw             8
audi            7
plymouth        7
saab            6
porsche         5
isuzu           4
jaguar          3
chevrolet       3
alfa-romero     3
renault         2
mercury         1
Name: brand, dtype: int64